# Twitter OAuth Setting
twitter_key:    <%= ENV['TWITTER_KEY'].to_s %>
twitter_secret: <%= ENV['TWITTER_SECRET'].to_s %>

# Facebook OAuth Setting
facebook_app_id:     '601219569953172'
facebook_app_secret: 'a7e3e8445b40cce8702511f08528dea9'

# GitHub OAuth Setting
github_client_id: <%= ENV['GITHUB_CLIENT_ID'].to_s %>
github_secret:    <%= ENV['GITHUB_SECRET'].to_s %>

# Gmail Pass
mail_password: <%= ENV['MAIL_PASSWORD'].to_s %>
